export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';

export const GET_SINGLE_RECIPE_SUCCESS = 'GET_SINGLE_RECIPE_SUCCESS';
export const GET_SINGLE_RECIPE_FAILURE = 'GET_SINGLE_RECIPE_FAILURE';

export const SET_SINGLE_RECIPE = 'SET_SINGLE_RECIPE';

export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_FAILURE = 'ADD_RECIPE_FAILURE';

export const MODIFY_RECIPE_SUCCESS = 'MODIFY_RECIPE_SUCCESS';
export const MODIFY_RECIPE_FAILURE = 'MODIFY_RECIPE_FAILURE';

export const FETCH_USER_RECIPES_SUCCESS = 'FETCH_USER_RECIPES_SUCCESS';
export const FETCH_USER_RECIPES_FAILURE = 'FETCH_USER_RECIPES_FAILURE';

export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAILURE = 'DELETE_RECIPE_FAILURE';

export const UPVOTE_SUCCESS = 'UPVOTE_SUCCESS';
export const UPVOTE_FAILURE = 'UPVOTE_FAILURE';

export const DOWNVOTE_SUCCESS = 'DOWNVOTE_SUCCESS';
export const DOWNVOTE_FAILURE = 'DOWNPVOTE_FAILURE';

export const FAVORITE_SUCCESS = 'FAVORITE_SUCCESS';
export const FAVORITE_FAILURE = 'FAVORITE_FAILURE';
