export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';

export const FETCH_RECIPE_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPE_FAILURE = 'FETCH_RECIPES_FAILURE';

