export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_FAILURE =  'CREATE_USER_FAILURE';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const LOGIN_USER_REQUEST = 'AUTHENTICATING_USER';
export const LOGIN_USER_FAILURE = 'AUTHENTICATION_FAILURE';
export const LOGIN_USER_SUCCESS = 'AUTHENTICATION_SUCCESSFUL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const LOG_OUT = 'LOGOUT_USER';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
