export const IS_AUTHENTICATING = 'IS_AUTHENTICATING';
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';

export const LOGIN_USER_REQUEST = 'AUTHENTICATING_USER';
export const LOGIN_USER_FAILURE = 'AUTHENTICATION_FAILURE';
export const LOGIN_USER_SUCCESS = 'AUTHENTICATION_SUCCESSFUL';

export const LOG_OUT = 'LOGOUT_USER';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER = 'SET_USER';
export const SET_CONTRIBUTION = 'SET_CONTRIBUTION';
