language: 
  - node_js

node_js:
  - '6.11.3'

cache:
  - npm install
  
branches:
  only:
  - develop
  
script:
  - npm run test
  - sequelize db:migrate --env test

services:
  - postgresql


before_script:
  - psql -c 'create database Testdb;' -U Andela
  - psql -c "CREATE USER Andela WITH PASSWORD 'andela';" -U Andela
  - sequelize db:seed:all

install:
  - npm install sequelize
  - npm install sequelize-cli
  - npm install pg
  - npm install pg-hstore

  

