language: 
  - node_js
node_js:
  - '8'
cache:
  - npm install
  
branches:
  only:
    - develop
services: 
  - postgresql

before_script:
  - psql -c 'create database Testdb;' -U postgres
  - cp .env.travis .env
  
install:
  - npm install sequelize
  - npm install sequelize-cli
  - npm install pg
  - npm install pg-hstore
addons:
  postgresql: "9.6"