language: 
  - node_js
install:
  - npm install -g codecov
script:
  - "jest": {
  "coverageDirectory": "./coverage/",
  "collectCoverage": true
    }
  - codecov
node_js:
  - '8'
cache:
  - npm install
  
branches:
  only:
    - develop
services: 
  - postgresql

after_script:
  - npm run coveralls

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
install:
  - npm install sequelize
  - npm install sequelize-cli
  - npm install pg
  - npm install pg-hstore

addons:
  postgresql: "9.6"