language: 
  - node_js

node_js:
  - '6.11.3'

cache:
  - npm install,
  
branches:
  only:
  - develop
  
script:
  - npm run test

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
