language: 
  - node_js

node_js:
  - '6.11.3'

cache:
  - npm install,
  
branches:
  only:
  - develop
  
script:
  - npm run test

services:
  - postgresql


before_script:
  - psql -c 'create database Testdb;' -U Andela W andela

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS docman_test;'


install:
  - npm install sequelize
  - npm install sequelize-cli
  - npm install pg
  - npm install pg-hstore

script:
  - sequelize db:migrate --env test

