language: 
  - node_js
node_js:
  - 6.11.3
cache:
  - npm install
  
branches:
  only:
  - develop
install:
  - npm install sequelize
  - npm install sequelize-cli
  - npm install pg
  - npm install pg-hstore  
services:
  - postgresql
before_script:
  - psql -c 'create database Testdb;' -U postgres
  - psql -c "CREATE USER Andela WITH PASSWORD 'andela';" -U postgres
  - sequelize db:seed:all
  
  script:
  - npm run test
  - sequelize db:migrate --env test
