const e2eMocks = require('../__mocks__/e2eMocks');

const url = 'http://localhost:8000';

module.exports = {
  'Navigate Home Page and sign up': client =>
    client
      .url(url)
      .waitForElementVisible('body', 1000)
      .pause(1000)
      .waitForElementVisible('nav', 2000)
      .pause(1000)
      .waitForElementVisible('#banner', 1000)
      .pause(1000)
      .waitForElementVisible('h4', 1000)
      .pause(1000)
      .waitForElementVisible('.grid-holder', 1000)
      .pause(1000)
      .waitForElementVisible('#details', 1000)
      .pause(1000)
      .waitForElementVisible('.next', 1000)
      .pause(1000)
      .waitForElementVisible('#signin', 1000)
      .pause(2000)
      .click('#signin')
      .pause(2000)
      .waitForElementVisible('#signuplink', 1000)
      .pause(2000)
      .click('#signuplink')
      .pause(2000)
      .waitForElementVisible('.form-horizontal', 2000)
      .click('#registerbutton')
      .pause(1000)
      .setValue('input[name=name]', e2eMocks.name)
      .pause(1000)
      .setValue('input[name=email]', e2eMocks.email)
      .pause(1000)
      .setValue('input[name=username]', e2eMocks.username)
      .pause(1000)
      .setValue('input[name=password]', e2eMocks.password)
      .pause(1000)
      .setValue('input[name=confirmPassword]', e2eMocks.password)
      .pause(1000)
      .click('#registerbutton')
      .pause(1000)
      .waitForElementVisible('.grid-holder', 3000)
      .pause(1000)
      .waitForElementVisible('.nav-item.dropdown', 3000)
      .pause(6000)
      .click('.nav-link.dropdown-toggle')
      .pause(3000)
      .waitForElementVisible('#signout', 7000)
      .click('#signout')
      .pause(1000),

  'Sign in and search': client =>
    client
      .waitForElementVisible('#signinpage', 1000)
      .pause(1000)
      .waitForElementVisible('#signinbtn', 1000)
      .click('#signinbtn')
      .pause(1000)
      .setValue('input[name=username]', 'john')
      .pause(1000)
      .setValue('input[name=password]', 'andela')
      .click('#signinbtn')
      .pause(1000)
      .click('#searchbtn')
      .pause(1000)
      .setValue('input[name=searchInput]', e2eMocks.invalidSearch)
      .click('#searchbtn')
      .pause(1000)
      .clearValue('input[name=searchInput]')
      .pause(2000)
      .setValue('input[name=searchInput]', e2eMocks.validSearch)
      .click('#searchbtn')
      .pause(1000),

  'create and edit recipe': client =>
    client
      .waitForElementVisible('nav', 3000)
      .click('#favorites')
      .pause(1000)
      .click('#myRecipes')
      .waitForElementVisible('#userRecipes', 5000)
      .click('#createRecipe')
      .pause(1000)
      .waitForElementVisible('#recipeForm', 1000)
      .click('#addRecipebtn')
      .pause(3000)
      .setValue('input[name=recipeName]', e2eMocks.recipeName)
      .setValue('textarea[name=ingredients]', e2eMocks.ingredients)
      .setValue('textarea[name=instructions]', e2eMocks.intsructions)
      .click('#addRecipebtn')
      .pause(3000)
      .waitForElementVisible('#userRecipe', 2000)
      .waitForElementVisible('.recipeName', 1000)
      .pause(2000)
      .click('.recipeName')
      .setValue('input[name=recipeName]', 'the new recipe name')
      .click('#addRecipebtn')
      .pause(3000)
      .waitForElementVisible('#userRecipe', 2000)
      .pause(3000)
      .click('.btn-danger')
      .pause(3000)
      .waitForElementVisible('.react-confirm-alert', 5000)
      .click('#confirmbtn')
      .pause(4000)
      .waitForElementVisible('#userRecipe', 2000)
      .click('.navbar-brand')
      .pause(3000),

  'Recipe details and ratings': client =>
    client
      .waitForElementVisible('.container.bg-3.text-center.main-content', 2000)
      .click('#details')
      .pause(1000)
      .waitForElementVisible('#ratings', 1000)
      .click('#upvote')
      .pause(5000)
      .click('#favorite')
      .pause(5000)
      .click('#downvote')
      .pause(5000)
      .waitForElementVisible('#reviewform', 2000)
      .setValue('textarea[name=comment]', e2eMocks.review)
      .pause(1000)
      .click('#reviewbtn')
      .pause(15000)
      .click('.navbar-brand')
      .pause(2000)
      .end()
};
